# coding: utf-8

"""
    Public API Gateway

    osparc-simcore Public RESTful API Specifications  # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import osparc
from osparc.api.token_api import TokenApi  # noqa: E501
from osparc.rest import ApiException


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self):
        self.api = osparc.api.token_api.TokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_for_access_token_v0_token_post(self):
        """Test case for for_access_token_v0_token_post

        Login For Access Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
