# coding: utf-8

"""
    Public API Gateway

    osparc-simcore Public RESTful API Specifications  # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import osparc
from osparc.api.user_api import UserApi  # noqa: E501
from osparc.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = osparc.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_my_profile_v0_user_get(self):
        """Test case for my_profile_v0_user_get

        Get My Profile  # noqa: E501
        """
        pass

    def test_my_profile_v0_user_patch(self):
        """Test case for my_profile_v0_user_patch

        Update My Profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
