# coding: utf-8

"""
    osparc public web api

    
    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import osparc
from osparc.api.solvers_api import SolversApi  # noqa: E501
from osparc.rest import ApiException


class TestSolversApi(unittest.TestCase):
    """SolversApi unit test stubs"""

    def setUp(self):
        self.api = osparc.api.solvers_api.SolversApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_job(self):
        """Test case for create_job

        Create Job  # noqa: E501
        """
        pass

    def test_get_solver(self):
        """Test case for get_solver

        Get Solver  # noqa: E501
        """
        pass

    def test_get_solver_by_name_and_version(self):
        """Test case for get_solver_by_name_and_version

        Get Solver By Name And Version  # noqa: E501
        """
        pass

    def test_list_jobs(self):
        """Test case for list_jobs

        List Jobs  # noqa: E501
        """
        pass

    def test_list_solvers(self):
        """Test case for list_solvers

        List Solvers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
