# coding: utf-8

"""
    Public API Server

    **osparc-simcore Public RESTful API Specifications** ## Python Library - Check the [documentation](https://itisfoundation.github.io/osparc-simcore-python-client) - Quick install: ``pip install git+https://github.com/ITISFoundation/osparc-simcore-python-client.git``   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import osparc
from osparc.models.file_metadata import FileMetadata  # noqa: E501
from osparc.rest import ApiException

class TestFileMetadata(unittest.TestCase):
    """FileMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FileMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = osparc.models.file_metadata.FileMetadata()  # noqa: E501
        if include_optional :
            return FileMetadata(
                file_id = '0', 
                filename = '0', 
                content_type = '0', 
                checksum = '0'
            )
        else :
            return FileMetadata(
                filename = '0',
        )

    def testFileMetadata(self):
        """Test FileMetadata"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
