# coding: utf-8

"""
    Public API Server

    **osparc-simcore Public RESTful API Specifications** ## Python Library - Check the [documentation](https://itisfoundation.github.io/osparc-simcore-python-client) - Quick install: ``pip install git+https://github.com/ITISFoundation/osparc-simcore-python-client.git``   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import osparc
from osparc.api.jobs_api import JobsApi  # noqa: E501
from osparc.rest import ApiException


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self):
        self.api = osparc.api.jobs_api.JobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job(self):
        """Test case for get_job

        Get Job  # noqa: E501
        """
        pass

    def test_get_job_output(self):
        """Test case for get_job_output

        Get Job Output  # noqa: E501
        """
        pass

    def test_inspect_job(self):
        """Test case for inspect_job

        Inspect Job  # noqa: E501
        """
        pass

    def test_list_all_jobs(self):
        """Test case for list_all_jobs

        List All Jobs  # noqa: E501
        """
        pass

    def test_list_job_outputs(self):
        """Test case for list_job_outputs

        List Job Outputs  # noqa: E501
        """
        pass

    def test_start_job(self):
        """Test case for start_job

        Start Job  # noqa: E501
        """
        pass

    def test_stop_job(self):
        """Test case for stop_job

        Stop Job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
