# coding: utf-8

"""
    Public API Gateway

    osparc-simcore Public RESTful API Specifications  # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import osparc
from osparc.api.studies_api import StudiesApi  # noqa: E501
from osparc.rest import ApiException


class TestStudiesApi(unittest.TestCase):
    """StudiesApi unit test stubs"""

    def setUp(self):
        self.api = osparc.api.studies_api.StudiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_studies_v0_studies_get(self):
        """Test case for studies_v0_studies_get

        List Studies  # noqa: E501
        """
        pass

    def test_study_v0_studies_post(self):
        """Test case for study_v0_studies_post

        Create Study  # noqa: E501
        """
        pass

    def test_study_v0_studies_study_id_delete(self):
        """Test case for study_v0_studies_study_id_delete

        Delete Study  # noqa: E501
        """
        pass

    def test_study_v0_studies_study_id_get(self):
        """Test case for study_v0_studies_study_id_get

        Get Study  # noqa: E501
        """
        pass

    def test_study_v0_studies_study_id_patch(self):
        """Test case for study_v0_studies_study_id_patch

        Update Study  # noqa: E501
        """
        pass

    def test_study_v0_studies_study_id_put(self):
        """Test case for study_v0_studies_study_id_put

        Replace Study  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
