# coding: utf-8

"""
    Public API Gateway

    osparc-simcore Public RESTful API Specifications  # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import osparc
from osparc.models.body_login_for_access_token_v0_token_post import BodyLoginForAccessTokenV0TokenPost  # noqa: E501
from osparc.rest import ApiException

class TestBodyLoginForAccessTokenV0TokenPost(unittest.TestCase):
    """BodyLoginForAccessTokenV0TokenPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BodyLoginForAccessTokenV0TokenPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = osparc.models.body_login_for_access_token_v0_token_post.BodyLoginForAccessTokenV0TokenPost()  # noqa: E501
        if include_optional :
            return BodyLoginForAccessTokenV0TokenPost(
                grant_type = 'a', 
                username = '0', 
                password = '0', 
                scope = '0', 
                client_id = '0', 
                client_secret = '0'
            )
        else :
            return BodyLoginForAccessTokenV0TokenPost(
                username = '0',
                password = '0',
        )

    def testBodyLoginForAccessTokenV0TokenPost(self):
        """Test BodyLoginForAccessTokenV0TokenPost"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
