# coding: utf-8

"""
    Public API Gateway

    osparc-simcore Public RESTful API Specifications  # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import osparc
from osparc.api.default_api import DefaultApi  # noqa: E501
from osparc.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = osparc.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_service_health_health_get(self):
        """Test case for service_health_health_get

        Check Service Health  # noqa: E501
        """
        pass

    def test_service_metadata_meta_get(self):
        """Test case for service_metadata_meta_get

        Get Service Metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
