# coding: utf-8

"""
    Public API Server

    **osparc-simcore Public RESTful API Specifications** ## Python Library - Check the [documentation](https://itisfoundation.github.io/osparc-simcore-python-client) - Quick install: ``pip install git+https://github.com/ITISFoundation/osparc-simcore-python-client.git``   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import osparc
from osparc.api.files_api import FilesApi  # noqa: E501
from osparc.rest import ApiException


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self):
        self.api = osparc.api.files_api.FilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_file(self):
        """Test case for download_file

        Download File  # noqa: E501
        """
        pass

    def test_get_file(self):
        """Test case for get_file

        Get File  # noqa: E501
        """
        pass

    def test_list_files(self):
        """Test case for list_files

        List Files  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        Upload File  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
