# coding: utf-8

"""
    osparc public web api

    
    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import osparc
from osparc.models.job_input import JobInput  # noqa: E501
from osparc.rest import ApiException

class TestJobInput(unittest.TestCase):
    """JobInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JobInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = osparc.models.job_input.JobInput()  # noqa: E501
        if include_optional :
            return JobInput(
                name = 'T', 
                type = 'number', 
                title = 'Temperature', 
                value = 33
            )
        else :
            return JobInput(
                name = 'T',
        )

    def testJobInput(self):
        """Test JobInput"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
