# coding: utf-8

"""
    osparc.io web API

    osparc-simcore public web API specifications  # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

from osparc import Solver  # noqa: E501


class TestSolver(unittest.TestCase):
    """Solver unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Solver
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # model = osparc.models.solver.Solver()  # noqa: E501
        if include_optional:
            return Solver(
                id="simcore/services/comp/sleeper",
                version="0.5.0",
                title="0",
                description="0",
                maintainer="0",
                url="0",
            )
        else:
            return Solver(
                id="simcore/services/comp/sleeper",
                version="0.5.0",
                title="0",
                maintainer="0",
                url="0",
            )

    def testSolver(self):
        """Test Solver"""
        self.make_instance(include_optional=False)
        self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
