# coding: utf-8

"""
    osparc.io web API

    osparc-simcore public web API specifications  # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

from osparc import HTTPValidationError  # noqa: E501
from osparc import ValidationError


class TestHTTPValidationError(unittest.TestCase):
    """HTTPValidationError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test HTTPValidationError
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # model = osparc.models.http_validation_error.HTTPValidationError()  # noqa: E501
        if include_optional:
            return HTTPValidationError(
                errors=[
                    ValidationError(
                        loc=["0"],
                        msg="0",
                        type="0",
                    )
                ]
            )
        else:
            return HTTPValidationError()

    def testHTTPValidationError(self):
        """Test HTTPValidationError"""
        self.make_instance(include_optional=False)
        self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
