# coding: utf-8

"""
    osparc.io web API

    osparc-simcore public web API specifications  # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

from osparc import JobInputs  # noqa: E501


class TestJobInputs(unittest.TestCase):
    """JobInputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JobInputs
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # model = osparc.models.job_inputs.JobInputs()  # noqa: E501
        if include_optional:
            return JobInputs(values={"key": 42})
        else:
            return JobInputs(
                values={"key": 3.14},
            )

    def testJobInputs(self):
        """Test JobInputs"""
        self.make_instance(include_optional=False)
        self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
