# coding: utf-8

"""
    osparc_client.io web API

    osparc_client-simcore public web API specifications  # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import osparc_client
from osparc_client.models.groups import Groups  # noqa: E501
from osparc_client.exceptions import ApiException

class TestGroups(unittest.TestCase):
    """Groups unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Groups
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = osparc_client.models.groups.Groups()  # noqa: E501
        if include_optional :
            return Groups(
                me = osparc_client.models.users_group.UsersGroup(
                    gid = '0',
                    label = '0',
                    description = '0', ),
                organizations = [
                    osparc_client.models.users_group.UsersGroup(
                        gid = '0',
                        label = '0',
                        description = '0', )
                    ],
                all = osparc_client.models.users_group.UsersGroup(
                    gid = '0',
                    label = '0',
                    description = '0', )
            )
        else :
            return Groups(
                me = osparc_client.models.users_group.UsersGroup(
                    gid = '0',
                    label = '0',
                    description = '0', ),
                all = osparc_client.models.users_group.UsersGroup(
                    gid = '0',
                    label = '0',
                    description = '0', ),
        )

    def testGroups(self):
        """Test Groups"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
