# coding: utf-8

"""
    osparc_client.io web API

    osparc_client-simcore public web API specifications  # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import osparc_client
from osparc_client.models.job import Job  # noqa: E501
from osparc_client.exceptions import ApiException

class TestJob(unittest.TestCase):
    """Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Job
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = osparc_client.models.job.Job()  # noqa: E501
        if include_optional :
            return Job(
                id = '0',
                name = 'a',
                inputs_checksum = '0',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                runner_name = 'a',
                url = '0',
                runner_url = '0',
                outputs_url = '0'
            )
        else :
            return Job(
                id = '0',
                name = 'a',
                inputs_checksum = '0',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                runner_name = 'a',
                url = '0',
                runner_url = '0',
                outputs_url = '0',
        )

    def testJob(self):
        """Test Job"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
